### ISSUE TITLE
Zonnon on GNU/Linux

### ISSUE THREAD

**Issue by ghost** [zonnonproject/compiler#1]
Was this project version tested with last GNU/Linux Mono and Eclipse versions?. 

I have seen this http://www.zonnon.ethz.ch/compiler/eclipse.html but it is used an older version...

**Comment by rmitin** [comment]
This version works with Mono. Command line was tested. However, if you compile the head from this repository, it might be less stable than the latest release on ETH webpage.

The eclipse plugin that is on zonnon.ethz.ch page is too old and hence not compatible with any current Eclipse. I do have a slightly fixed plugin version here http://mitin.ch/archive/

This plugin is a very trivial compiler launcher. It is not a full integration.

I didn't do any improvements on the plugin, just corrected the dependencies quite some time ago (then it was tested with Mars release of Eclipse). There I also added a PDF with screenshots what to verify when unpacking the ZIP into Marse release of Eclipse.
We still need to unpack the ZIP so the plugin can call the compiler contained in that ZIP.

**Comment by ghost** [comment]
Thank you.
